config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :students do
    resources :completed_lesson_parts, module: :students, only: [:create, :new]
  end
  resources :teachers, only: [:index, :show] do
    resources :teaches_students, module: :teachers, only: :index
  end
end

app/models/teacher.rb
# models a teacher teaching a class
class Teacher < ApplicationRecord
  has_many :school_classes, dependent: :nullify, inverse_of: :teacher

  validates :email, format: { with: /\A.+@.+\z/ }, length: { maximum: 255 }, presence: true, uniqueness: true
  validates :name, length: { maximum: 255 }, presence: true
end

app/controllers/teachers/teaches_students_controller.rb
module Teachers
  # Shows a how teachers relate to students
  class TeachesStudentsController < ApplicationController
    before_action :set_teacher

    def index
      @students = Student.taught_by(@teacher)
    end

    private

      def set_teacher
        @teacher = Teacher.find(params[:teacher_id])
      end
  end
end

app/controllers/teachers_controller.rb
# Handle requests relating to a teacher
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show]

  def index
    @teachers = Teacher.order(:name)
  end

  def show
  end

  private

    def set_teacher
      @teacher = Teacher.find(params[:id])
    end
end

app/helpers/teachers/teaches_students_helper.rb
module Teachers
  module TeachesStudentsHelper # :nodoc:
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper # :nodoc:
end

app/views/teachers/_teacher.html.erb
<li class="list-group-item">
  <%= link_to teacher.name, teacher_path(teacher), class: 'd-b' %>
</li>

app/views/teachers/index.html.erb
<h2><%= t('.heading') %></h2>

<div class="row">
  <div class="col-sm-8">
    <ul class="list-group">
      <%= render @teachers %>
    </ul>
  </div>
</div>

app/views/teachers/show.html.erb
<h2><%= @teacher.name %></h2>

<dl class="dl-horizontal">
  <dt><%= t('.email') %></dt>
  <dd><%= @teacher.email %></dd>
</dl>

<div>
  <%= link_to t('.students_taught'),
              teacher_teaches_students_path(teacher_id: @teacher),
              class: 'btn btn-default btn-lg' %>
</div>