config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :students do
    resources :completed_lesson_parts, module: :students, only: [:create, :new]
  end
  resources :teachers, only: [:index, :show] do
    resources :teaches_students, module: :teachers, only: :index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base # :nodoc:
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper # :nodoc:
end

app/views/application/_messages.html.erb
<%= content_tag :div, flash[:notice], class: 'alert alert-success' if flash.key?(:notice) %>
<%= content_tag :div, flash[:alert], class: 'alert alert-danger' if flash.key?(:alert) %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#main-navbar"
              aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to t('.home'), root_url, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('.students'), students_path %></li>
        <li><%= link_to t('.teachers'), teachers_path %></li>
      </ul>
    </div>
  </div>
</nav>